// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZS2SiSI_NS1a3oLiGY7G14KHsPOa58E',
    appId: '1:914060843169:web:4b1d7073f3bb8bea6778e0',
    messagingSenderId: '914060843169',
    projectId: 'project-5efbf',
    authDomain: 'project-5efbf.firebaseapp.com',
    storageBucket: 'project-5efbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTHUlM0pnnRICCiiSrXlsqLSQpmJqsvs',
    appId: '1:914060843169:android:cdfb2334dc9db02d6778e0',
    messagingSenderId: '914060843169',
    projectId: 'project-5efbf',
    storageBucket: 'project-5efbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjPG3Km6WsoYHNUz6V8ecpVf9w7Mf3_g',
    appId: '1:914060843169:ios:5a876181d67ac0536778e0',
    messagingSenderId: '914060843169',
    projectId: 'project-5efbf',
    storageBucket: 'project-5efbf.appspot.com',
    iosClientId: '914060843169-2l6kjg4mj4kadqqtlh9ks9gjhovkfs01.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjPG3Km6WsoYHNUz6V8ecpVf9w7Mf3_g',
    appId: '1:914060843169:ios:2365cef813481e586778e0',
    messagingSenderId: '914060843169',
    projectId: 'project-5efbf',
    storageBucket: 'project-5efbf.appspot.com',
    iosClientId: '914060843169-kdnplcvoji3icp0bi257ac19n61npdk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
